on: [push, pull_request]
name: lint
jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
          toolchain: 1.85.0
      - run: cargo fmt --all -- --check

  clippy-crypto-openssl:
    name: cargo clippy crypto-openssl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          toolchain: 1.85.0
      - run: cargo clippy --features=crypto-openssl,hw_tests,dangerous_hw_tests --all-targets -- -D clippy::all -D unused_imports -D warnings -D clippy::style

  clippy-crypto-rust:
    name: cargo clippy crypto-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          toolchain: 1.85.0
      - run: cargo clippy --no-default-features --features=snp,evidence,verifier,endorser,reference,crypto-rust,hw_tests,dangerous_hw_tests --all-targets -- -D clippy::all -D unused_imports -D warnings -D clippy::style

  readme:
    name: cargo rdme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0
      - run: |
          cargo install cargo-rdme --version 1.4.8 --locked
          cargo rdme --check --no-fail-on-warnings

  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: enarx/spdx@master
        with:
          licenses: Apache-2.0
