on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

name: release
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y asciidoctor musl-tools
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --target x86_64-unknown-linux-musl
      - uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-musl/release/snpguest
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
